CREATE TABLE DB2INST1.TBLNEWS  ( 
    NEWS_ITEM    	INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20) NOT NULL,
    DATE_BEGIN   	TIMESTAMP,
    DATE_END     	TIMESTAMP,
    TITLE        	VARCHAR(255),
    CONTENT      	VARCHAR(255),
    HEADER_COLOR 	VARCHAR(255),
    CONTENT_COLOR	VARCHAR(255),
    ISLOCKED     	VARCHAR(255),
    CONSTRAINT PK_USER_TEST PRIMARY KEY(NEWS_ITEM)
)
GO

